package acceptance

import (
	"context"
	"testing"

	"github.com/gdql/gdql/run"
	"github.com/stretchr/testify/require"
)

// TestDocsQueries verifies every GDQL query in the documentation
// produces a non-empty result against the embedded database.
// Generated from docs — do not edit by hand.
func TestDocsQueries(t *testing.T) {
	queries := []struct {
		file  string
		query string
	}{
		{"examples.md", "SHOWS FROM 1977;"},
		{"examples.md", "SHOWS FROM 77;"},
		{"examples.md", "SHOWS FROM 1977-1980 ORDER BY DATE;"},
		{"examples.md", "SHOWS FROM 1972 ORDER BY DATE DESC LIMIT 5;"},
		{"examples.md", "SHOWS AT \"Fillmore West\" FROM 1969;"},
		{"examples.md", "SHOWS AT \"Winterland\" FROM 1977;"},
		{"examples.md", "SHOWS AT \"New York\" LIMIT 20;"},
		{"examples.md", "SHOWS AT \"Madison Square Garden\" LIMIT 10;"},
		{"examples.md", "SHOWS FROM 77-80 WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\";"},
		{"examples.md", "SHOWS WHERE \"Help on the Way\" > \"Slipknot!\" > \"Franklin's Tower\";"},
		{"examples.md", "SHOWS WHERE \"China Cat Sunflower\" INTO \"I Know You Rider\";"},
		{"examples.md", "SHOWS WHERE \"Estimated Prophet\" THEN \"Eyes of the World\";"},
		{"examples.md", "SHOWS WHERE \"Dark Star\" -> \"Saint Stephen\";"},
		{"examples.md", "COUNT \"Dark Star\";"},
		{"examples.md", "COUNT \"Scarlet Begonias\";"},
		{"examples.md", "COUNT \"Dark Star\" FROM 1972-1974;"},
		{"examples.md", "COUNT \"Scarlet Begonias\" AFTER 1977;"},
		{"examples.md", "COUNT \"Saint Stephen\" BEFORE 1972;"},
		{"examples.md", "SHOWS WHERE SET1 OPENED \"Jack Straw\";"},
		{"examples.md", "SHOWS WHERE OPENER \"Bertha\";"},
		{"examples.md", "SHOWS WHERE SET2 CLOSED \"Sugar Magnolia\";"},
		{"examples.md", "SHOWS WHERE ENCORE = \"U.S. Blues\";"},
		{"examples.md", "SHOWS WHERE ENCORE = \"One More Saturday Night\";"},
		{"examples.md", "SHOWS WHERE CLOSER \"Morning Dew\";"},
		{"examples.md", "SHOWS WHERE PLAYED \"Dark Star\" AND PLAYED \"Saint Stephen\";"},
		{"examples.md", "SHOWS FROM 1977 WHERE PLAYED \"Eyes of the World\";"},
		{"examples.md", "SHOWS FROM 1977 WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\" AND PLAYED \"Estimated Prophet\";"},
		{"examples.md", "SHOWS AT \"Winterland\" WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\";"},
		{"examples.md", "SHOWS WHERE SET1 OPENED \"Jack Straw\" AND PLAYED \"Deal\";"},
		{"examples.md", "SETLIST FOR 5/8/77;"},
		{"examples.md", "SETLIST FOR 12/31/78;"},
		{"examples.md", "SETLIST FOR 8/27/72;"},
		{"examples.md", "SONGS WITH LYRICS(\"sun\");"},
		{"examples.md", "SONGS WITH LYRICS(\"train\", \"road\");"},
		{"examples.md", "SONGS WITH LYRICS(\"rose\") AS COUNT;"},
		{"examples.md", "PERFORMANCES OF \"Dark Star\";"},
		{"examples.md", "PERFORMANCES OF \"Dark Star\" FROM 1972-1974;"},
		{"examples.md", "PERFORMANCES OF \"Scarlet Begonias\" FROM 77-79 ORDER BY DATE DESC LIMIT 20;"},
		{"examples.md", "SHOWS FROM 1977 LIMIT 3 AS TABLE;"},
		{"examples.md", "SHOWS FROM 1977 LIMIT 3 AS JSON;"},
		{"examples.md", "SHOWS FROM 1977 LIMIT 3 AS CSV;"},
		{"getting-started.md", "SHOWS FROM 1977 LIMIT 5;"},
		{"getting-started.md", "SHOWS FROM 1977 LIMIT 5 AS JSON;"},
		{"advanced.md", "SHOWS WHERE PLAYED \"Dark Star\" AND NOT PLAYED \"Saint Stephen\" LIMIT 10;"},
		{"advanced.md", "SHOWS AFTER 1980 WHERE PLAYED \"Scarlet Begonias\" AND NOT PLAYED \"Fire on the Mountain\" LIMIT 10;"},
		{"advanced.md", "SHOWS WHERE PLAYED \"Truckin'\" AND NOT \"Drums\" LIMIT 10;"},
		{"advanced.md", "SHOWS AT \"Winterland\" FROM 1977-1978 WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\" AND PLAYED \"Estimated Prophet\" ORDER BY DATE LIMIT 10;"},
		{"advanced.md", "SHOWS AT \"Fillmore\" FROM 1969 WHERE OPENER \"Dark Star\" AND PLAYED \"Saint Stephen\";"},
		{"advanced.md", "COUNT \"Eyes of the World\" FROM 1974;"},
		{"advanced.md", "SHOWS WHERE \"Help on the Way\" > \"Slipknot!\" > \"Franklin's Tower\" AND PLAYED \"Dark Star\";"},
		{"advanced.md", "SHOWS AT \"Fillmore West\" WHERE \"Dark Star\" > \"Saint Stephen\" > \"The Eleven\" ORDER BY DATE;"},
		{"advanced.md", "SHOWS AT \"Spectrum\" WHERE \"China Cat Sunflower\" > \"I Know You Rider\";"},
		{"advanced.md", "SHOWS WHERE OPENER (\"Help on the Way\" > \"Slipknot!\");"},
		{"advanced.md", "SHOWS WHERE OPENER (\"Help on the Way\" > \"Slipknot!\") AND CLOSER \"Brokedown Palace\";"},
		{"advanced.md", "SHOWS WHERE CLOSER (\"Throwin' Stones\" > \"Not Fade Away\");"},
		{"advanced.md", "SHOWS FROM 1979-1981 WHERE OPENER \"Bertha\" ORDER BY DATE;"},
		{"advanced.md", "SHOWS AFTER 1985 WHERE CLOSER \"Morning Dew\" ORDER BY DATE;"},
		{"advanced.md", "COUNT \"Dark Star\" FROM BRENT_ERA;"},
		{"advanced.md", "COUNT SHOWS BEFORE 1976;"},
		{"advanced.md", "COUNT SHOWS WHERE \"Help on the Way\" > \"Slipknot!\" > \"Franklin's Tower\";"},
		{"advanced.md", "COUNT SHOWS WHERE OPENER \"Bertha\";"},
		{"advanced.md", "SONGS WITH LYRICS(\"sun\", \"shine\") AS COUNT;"},
		{"advanced.md", "FIRST \"Help on the Way\";"},
		{"advanced.md", "LAST \"Saint Stephen\";"},
		{"advanced.md", "LAST \"Dark Star\";"},
		{"advanced.md", "COUNT SHOWS FROM PRIMAL;"},
		{"advanced.md", "COUNT SHOWS FROM EUROPE72;"},
		{"advanced.md", "COUNT SHOWS FROM BRENT_ERA;"},
		{"advanced.md", "COUNT SHOWS FROM VINCE_ERA;"},
		{"advanced.md", "RANDOM SHOW FROM PRIMAL;"},
		{"advanced.md", "RANDOM SHOW FROM EUROPE72;"},
		{"advanced.md", "RANDOM SHOW FROM BRENT_ERA;"},
		{"advanced.md", "SONGS WITH LYRICS(\"sun\", \"shine\");"},
		{"advanced.md", "SONGS WITH LYRICS(\"sun\") AND LYRICS(\"train\");"},
		{"advanced.md", "SHOWS AT \"Winterland\" FROM 1977 LIMIT 5 AS JSON;"},
		{"advanced.md", "SHOWS AT \"Winterland\" FROM 1977 LIMIT 5 AS CSV;"},
		{"advanced.md", "SHOWS AT \"Barton Hall\";"},
		{"advanced.md", "SHOWS WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\" AND PLAYED \"Morning Dew\" ORDER BY DATE;"},
		{"syntax-highlighting.md", "SHOWS FROM 1977 WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\";"},
		{"syntax-highlighting.md", "COUNT \"Dark Star\" AFTER 1988;"},
		{"reference/setlist.md", "SETLIST FOR 3/29/90;"},
		{"reference/setlist.md", "SETLIST FOR 5/7/77;"},
		{"reference/setlist.md", "SETLIST FOR 5/9/77;"},
		{"reference/setlist.md", "SETLIST FOR 5/8/77 AS JSON;"},
		{"reference/setlist.md", "SETLIST FOR 5/8/77 AS CSV;"},
		{"reference/conventions.md", "setlist for 5/8/77;"},
		{"reference/conventions.md", "Shows From 1977 Limit 5;"},
		{"reference/conventions.md", "PERFORMANCES OF \"Eyes of the World\";"},
		{"reference/conventions.md", "SHOWS AT \"Winterland\";"},
		{"reference/conventions.md", "SHOWS WHERE PLAYED \"Scarlet Begonias\";"},
		{"reference/conventions.md", "SONGS WITH LYRICS(\"train\");"},
		{"reference/performances.md", "PERFORMANCES OF \"Scarlet Begonias\";"},
		{"reference/performances.md", "PERFORMANCES OF \"Dark Star\" FROM 1972;"},
		{"reference/performances.md", "PERFORMANCES OF \"Eyes of the World\" FROM 1974-1977;"},
		{"reference/performances.md", "PERFORMANCES OF \"Dark Star\" ORDER BY DATE LIMIT 10;"},
		{"reference/performances.md", "PERFORMANCES OF \"Help on the Way\" ORDER BY DATE LIMIT 1;"},
		{"reference/operators.md", "SHOWS WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\";"},
		{"reference/operators.md", "SHOWS WHERE \"Scarlet Begonias\" >> \"Fire on the Mountain\";"},
		{"reference/operators.md", "SHOWS WHERE PLAYED \"Dark Star\" AND NOT PLAYED \"Saint Stephen\";"},
		{"reference/operators.md", "SHOWS FROM 77-80;"},
		{"reference/operators.md", "SHOWS FROM PRIMAL;"},
		{"reference/operators.md", "SHOWS BEFORE 1976;"},
		{"reference/operators.md", "SHOWS AFTER 1985;"},
		{"reference/operators.md", "SHOWS FROM 1977 LIMIT 3 AS SETLIST;"},
		{"reference/shows.md", "SHOWS;"},
		{"reference/shows.md", "SHOWS LIMIT 20;"},
		{"reference/shows.md", "SHOWS FROM 1977-1980;"},
		{"reference/shows.md", "SHOWS FROM 77-80 LIMIT 10;"},
		{"reference/shows.md", "SHOWS FROM EUROPE72;"},
		{"reference/shows.md", "SHOWS FROM BRENT_ERA;"},
		{"reference/shows.md", "SHOWS AT \"Fillmore West\";"},
		{"reference/shows.md", "SHOWS AT \"New York\" LIMIT 10;"},
		{"reference/shows.md", "SHOWS AT \"Madison Square Garden\";"},
		{"reference/shows.md", "SHOWS FROM 1990 WHERE PLAYED \"Eyes of the World\";"},
		{"reference/shows.md", "SHOWS FROM 1977 ORDER BY DATE;"},
		{"reference/shows.md", "SHOWS FROM 1977 ORDER BY DATE DESC;"},
		{"reference/shows.md", "SHOWS FROM 1977 LIMIT 3;"},
		{"reference/songs.md", "SONGS;"},
		{"reference/songs.md", "SONGS LIMIT 50;"},
		{"reference/songs.md", "SONGS ORDER BY NAME LIMIT 30;"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"rose\") LIMIT 20;"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"water\");"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"wheel\");"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"river\", \"deep\");"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"sun\") AND LYRICS(\"shine\");"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"train\") AND LYRICS(\"road\");"},
		{"reference/songs.md", "SONGS WITH LYRICS(\"sun\") AS COUNT;"},
		{"reference/_index.md", "SHOWS AT \"Winterland\" FROM 1977-1978 WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\" AND PLAYED \"Estimated Prophet\" ORDER BY DATE LIMIT 10 AS JSON;"},
		{"reference/where.md", "SHOWS WHERE SET1 OPENED \"Bertha\";"},
		{"reference/where.md", "SHOWS WHERE SET3 OPENED \"U.S. Blues\";"},
		{"reference/where.md", "SHOWS WHERE SET3 CLOSED \"Brokedown Palace\";"},
		{"reference/where.md", "SHOWS WHERE PLAYED \"Dark Star\";"},
		{"reference/where.md", "SHOWS WHERE PLAYED \"Scarlet Begonias\" AND PLAYED \"Fire on the Mountain\";"},
		{"reference/where.md", "SHOWS WHERE \"Scarlet Begonias\" > \"Fire on the Mountain\" AND PLAYED \"Estimated Prophet\";"},
	}
	for _, tc := range queries {
		t.Run(tc.query, func(t *testing.T) {
			result, err := run.RunWithEmbeddedDB(context.Background(), tc.query)
			require.NoError(t, err, "file: %s", tc.file)
			require.NotEmpty(t, result, "file: %s, query returned empty", tc.file)
			// Check for "No X found" responses
			require.NotContains(t, result, "\"count\":0", "file: %s, count was 0", tc.file)
		})
	}
}
